---
name: Next semantic-release version

on:
  workflow_call:
    outputs:
      new-release-published:
        description: Indicates whether a new release will be published. The value is a string, either 'true' or 'false'.
        value: ${{ jobs.get-next-version.outputs.new-release-published }}
      new-release-version:
        description: If a new release will be published, the version of the new release. The value is a string, for example '1.3.0'.
        value: ${{ jobs.get-next-version.outputs.new-release-version }}

jobs:
  get-next-version:
    name: Get next release version
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}
    steps:
      - id: get-next-version
        uses: semantic-release-action/next-release-version/internal@v3
